name: Deploy to Github pages

on:
  push:
    # this is the branch you develop site
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build site with Jekyll
      uses: jekyll/actions/jekyll@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run a multi-line script
      run: |
        echo test the checkout action,
        ls -a